//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.1433.
// 
#pragma warning disable 1591

namespace ConsoleApplication1.bossApi {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSToolSoap", Namespace="http://b-oss.ufon.cz/internalapi")]
    public partial class WSTool : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SetSubsAttributesOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateSubsAttributesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTool() {
            this.Url = global::ConsoleApplication1.Properties.Settings.Default.ConsoleApplication1_bossApi_WSTool;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SetSubsAttributesCompletedEventHandler SetSubsAttributesCompleted;
        
        /// <remarks/>
        public event UpdateSubsAttributesCompletedEventHandler UpdateSubsAttributesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://b-oss.ufon.cz/internalapi/SetSubsAttributes", RequestNamespace="http://b-oss.ufon.cz/internalapi", ResponseNamespace="http://b-oss.ufon.cz/internalapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RcStruct SetSubsAttributes(AttrCommandInfo[] cmd) {
            object[] results = this.Invoke("SetSubsAttributes", new object[] {
                        cmd});
            return ((RcStruct)(results[0]));
        }
        
        /// <remarks/>
        public void SetSubsAttributesAsync(AttrCommandInfo[] cmd) {
            this.SetSubsAttributesAsync(cmd, null);
        }
        
        /// <remarks/>
        public void SetSubsAttributesAsync(AttrCommandInfo[] cmd, object userState) {
            if ((this.SetSubsAttributesOperationCompleted == null)) {
                this.SetSubsAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSetSubsAttributesOperationCompleted);
            }
            this.InvokeAsync("SetSubsAttributes", new object[] {
                        cmd}, this.SetSubsAttributesOperationCompleted, userState);
        }
        
        private void OnSetSubsAttributesOperationCompleted(object arg) {
            if ((this.SetSubsAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SetSubsAttributesCompleted(this, new SetSubsAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://b-oss.ufon.cz/internalapi/UpdateSubsAttributes", RequestNamespace="http://b-oss.ufon.cz/internalapi", ResponseNamespace="http://b-oss.ufon.cz/internalapi", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public RcStruct UpdateSubsAttributes(string msisdn, string sType, string sCode, string sapId, string recWho, string recMe, string recSCode) {
            object[] results = this.Invoke("UpdateSubsAttributes", new object[] {
                        msisdn,
                        sType,
                        sCode,
                        sapId,
                        recWho,
                        recMe,
                        recSCode});
            return ((RcStruct)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateSubsAttributesAsync(string msisdn, string sType, string sCode, string sapId, string recWho, string recMe, string recSCode) {
            this.UpdateSubsAttributesAsync(msisdn, sType, sCode, sapId, recWho, recMe, recSCode, null);
        }
        
        /// <remarks/>
        public void UpdateSubsAttributesAsync(string msisdn, string sType, string sCode, string sapId, string recWho, string recMe, string recSCode, object userState) {
            if ((this.UpdateSubsAttributesOperationCompleted == null)) {
                this.UpdateSubsAttributesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateSubsAttributesOperationCompleted);
            }
            this.InvokeAsync("UpdateSubsAttributes", new object[] {
                        msisdn,
                        sType,
                        sCode,
                        sapId,
                        recWho,
                        recMe,
                        recSCode}, this.UpdateSubsAttributesOperationCompleted, userState);
        }
        
        private void OnUpdateSubsAttributesOperationCompleted(object arg) {
            if ((this.UpdateSubsAttributesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateSubsAttributesCompleted(this, new UpdateSubsAttributesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b-oss.ufon.cz/internalapi")]
    public partial class AttrCommandInfo {
        
        private string msisdnField;
        
        private string attr_nameField;
        
        private string attr_valueField;
        
        /// <remarks/>
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                this.msisdnField = value;
            }
        }
        
        /// <remarks/>
        public string attr_name {
            get {
                return this.attr_nameField;
            }
            set {
                this.attr_nameField = value;
            }
        }
        
        /// <remarks/>
        public string attr_value {
            get {
                return this.attr_valueField;
            }
            set {
                this.attr_valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://b-oss.ufon.cz/internalapi")]
    public partial class RcStruct {
        
        private int rcField;
        
        private string msgField;
        
        /// <remarks/>
        public int rc {
            get {
                return this.rcField;
            }
            set {
                this.rcField = value;
            }
        }
        
        /// <remarks/>
        public string msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void SetSubsAttributesCompletedEventHandler(object sender, SetSubsAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetSubsAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SetSubsAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RcStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RcStruct)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    public delegate void UpdateSubsAttributesCompletedEventHandler(object sender, UpdateSubsAttributesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.1433")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateSubsAttributesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateSubsAttributesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RcStruct Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RcStruct)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591